Repository 0NYE/FPS-backend, pull requests merged in 2023-05, with the labels that each got.

#6 Issue#3 image compare
  .gitignore
  server/app/__init__.py
  server/image_similarity/image_similarity_visual.py
  server/image_similarity/modified.png
  server/image_similarity/original.png
  venvs/active.cmd
Labels: feat

#8 [Feat#5] 이미지 유사도 측정 값을 전달하고 받기
  .gitignore
  server/app/__init__.py
  server/app/static/image/modified.png
  server/app/static/image/modifyResult.png
  server/app/static/image/original.png
  server/app/templates/index.html
  server/app/templates/result.html
  server/image_similarity/image_similarity_visual.py
  server/views/image_similarity/image_similarity_visual.py
  server/views/main_views.py
Labels: feat

#12 이미지 경로 관련 이슈 해결, 서버와 mysql 설정 완료, API 문서화
  server/apis/image_similarity_visual.py
  server/apis/problem_view.py
  server/config/config.ini
  server/modifyResult.png
Labels: feat

#19 Refactor/#14/api
  server/apis/image_similarity_visual.py
  server/apis/problem.py
  server/app/__init__.py
  server/app/static/image/Aris.jpg
  server/app/static/image/problem.png
  server/app/static/image/result.png
  server/app/static/image/submit.png
  server/app/static/result.png
  server/module/error_handler.py
Labels: refactor, feat

#22 회원가입, 로그인, 로그아웃 api 구현
  server/apis/auth.py
Labels: feat

#24 refactor: 로그인 api 수정
  server/apis/auth.py
  server/app/__init__.py
Labels: refactor

#26 fix: 로그인 세션 구현
  server/apis/auth.py
Labels: fix

#27 fix: 로그인 세션
  server/apis/auth.py
Labels: fix

#28 feat, fix : /compare 에러 예외처리 완료. /problems/submit 수정 중
  server/apis/auth.py
  server/apis/image_similarity_visual.py
  server/apis/problem.py
  server/apis/text.py
  server/app/static/result.png
Labels: feat, fix
